import { createClient } from '@supabase/supabase-js';
import * as jose from 'jose';
import QRCode from 'qrcode';
import { sendEmail } from '$lib/email/send';
import { getQRDailyEmail } from '$lib/email/templates/qr-daily';
import { todayInPT, endOfDayPT } from '$lib/utils/timezone';
import { randomUUID, sha256 } from '$lib/utils/crypto';

export async function issueDailyQRCodes(config: {
  supabaseUrl: string;
  supabaseServiceKey: string;
  qrPrivateKey: string;
}) {
  const supabase = createClient(config.supabaseUrl, config.supabaseServiceKey);
  const today = todayInPT(); // YYYY-MM-DD in Pacific Time

  console.log(`[QR Job] Starting QR issuance for ${today}`);

  // CRITICAL SAFETY CHECK: Alert on subscriptions with NULL period dates
  const { data: nullDateSubs, error: nullCheckError } = await supabase
    .from('subscriptions')
    .select('id, stripe_subscription_id, customers(email)')
    .eq('status', 'active')
    .or('current_period_start.is.null,current_period_end.is.null');

  if (nullCheckError) {
    console.error('[QR Job] Error checking for NULL dates:', nullCheckError);
  } else if (nullDateSubs && nullDateSubs.length > 0) {
    const alertMessage = `🚨 CRITICAL: ${nullDateSubs.length} active subscriptions have NULL period dates!\n\nThese customers will NOT receive QR codes:\n${nullDateSubs.map(s => {
      const customer = Array.isArray(s.customers) ? s.customers[0] : s.customers;
      return `- ${customer?.email} (${s.stripe_subscription_id})`;
    }).join('\n')}`;

    console.error('[QR Job] NULL DATE ALERT:', alertMessage);

    // Send alert via Telegram if bot token is available
    try {
      const { TELEGRAM_BOT_TOKEN } = await import('$env/static/private');
      const NOAH_TELEGRAM_ID = '1413464598'; // @noahchonlee

      await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: NOAH_TELEGRAM_ID,
          text: alertMessage,
          parse_mode: 'Markdown'
        })
      });
    } catch (alertError) {
      console.error('[QR Job] Failed to send NULL date alert:', alertError);
    }
  }

  // Get all active subscriptions where today falls within the PAID period
  // Critical: This prevents QR issuance if invoice payment failed
  const { data: subscriptions, error: subError } = await supabase
    .from('subscriptions')
    .select('*, customers(*)')
    .eq('status', 'active')
    .lte('current_period_start', today)  // Period has started
    .gte('current_period_end', today);   // Period hasn't ended

  if (subError) {
    console.error('[QR Job] Error fetching subscriptions:', subError);
    throw subError;
  }

  if (!subscriptions || subscriptions.length === 0) {
    console.log('[QR Job] No active subscriptions found');
    return { issued: 0, errors: [] };
  }

  console.log(`[QR Job] Found ${subscriptions.length} active subscriptions`);

  const results = {
    issued: 0,
    errors: [] as Array<{ customer_id: string; error: string }>
  };

  for (const subscription of subscriptions) {
    const customer = Array.isArray(subscription.customers)
      ? subscription.customers[0]
      : subscription.customers;

    if (!customer) {
      console.error(`[QR Job] No customer found for subscription ${subscription.id}`);
      continue;
    }

    try {
      // Check if customer has skipped this date
      const { data: skip } = await supabase
        .from('skips')
        .select('*')
        .eq('customer_id', customer.id)
        .eq('skip_date', today)
        .single();

      const mealsAllowed = skip ? 0 : 1;

      // Upsert entitlement for today
      await supabase
        .from('entitlements')
        .upsert({
          customer_id: customer.id,
          service_date: today,
          meals_allowed: mealsAllowed,
          meals_redeemed: 0
        }, {
          onConflict: 'customer_id,service_date'
        });

      // Skip QR generation if meal was skipped
      if (mealsAllowed === 0) {
        console.log(`[QR Job] Skipping QR for customer ${customer.id} - date skipped`);
        continue;
      }

      // Check if QR already exists for this customer + date (race condition check)
      const { data: existingQR } = await supabase
        .from('qr_tokens')
        .select('jti, issued_at')
        .eq('customer_id', customer.id)
        .eq('service_date', today)
        .single();

      let jti: string;
      let jwt: string;

      if (existingQR) {
        // QR already generated by another cron instance - skip generation
        console.log(`[QR Job] QR already exists for customer ${customer.id} on ${today} (issued at ${existingQR.issued_at})`);

        // Re-generate JWT from existing JTI to send in email/telegram
        jti = existingQR.jti;
        const expiresAt = endOfDayPT(today);
        const privateKey = await jose.importPKCS8(config.qrPrivateKey, 'ES256');

        jwt = await new jose.SignJWT({
          service_date: today
        })
          .setProtectedHeader({ alg: 'ES256' })
          .setIssuer('frontier-meals-kiosk')
          .setSubject(customer.id)
          .setJti(jti)
          .setIssuedAt()
          .setExpirationTime(Math.floor(expiresAt.getTime() / 1000))
          .sign(privateKey);
      } else {
        // Generate new QR code JWT
        jti = randomUUID();
        const expiresAt = endOfDayPT(today); // 11:59:59.999 PM PT (handles PST/PDT automatically)

        const privateKey = await jose.importPKCS8(config.qrPrivateKey, 'ES256');

        jwt = await new jose.SignJWT({
          service_date: today
        })
          .setProtectedHeader({ alg: 'ES256' })
          .setIssuer('frontier-meals-kiosk')
          .setSubject(customer.id)
          .setJti(jti)
          .setIssuedAt()
          .setExpirationTime(Math.floor(expiresAt.getTime() / 1000))
          .sign(privateKey);

        // Store QR token metadata using INSERT (not UPSERT)
        // This will fail with unique constraint violation if another cron already created it
        const { error: insertError } = await supabase
          .from('qr_tokens')
          .insert({
            customer_id: customer.id,
            service_date: today,
            jti,
            issued_at: new Date().toISOString(),
            expires_at: expiresAt.toISOString(),
            used_at: null
          });

        if (insertError) {
          // Check if it's a unique constraint violation (code 23505)
          if (insertError.code === '23505') {
            console.log(`[QR Job] Race condition detected for customer ${customer.id} - QR already created by another instance`);
            // Another cron instance created it between our check and insert - skip this customer
            continue;
          } else {
            // Other database error - throw to be caught by outer error handler
            throw insertError;
          }
        }

        console.log(`[QR Job] Created new QR token for customer ${customer.id}`);
      }

      // Generate QR code image (base64 data URL)
      const qrCodeDataUrl = await QRCode.toDataURL(jwt, {
        width: 280,
        margin: 2,
        color: {
          dark: '#000000',
          light: '#FFFFFF'
        }
      });

      // Send email with QR code
      const emailTemplate = getQRDailyEmail({
        customer_name: customer.name,
        service_date: today,
        qr_code_data_url: qrCodeDataUrl
      });

      await sendEmail({
        to: customer.email,
        subject: emailTemplate.subject,
        html: emailTemplate.html,
        tags: [
          { name: 'category', value: 'qr_daily' },
          { name: 'service_date', value: today },
          { name: 'customer_id', value: customer.id }
        ],
        idempotencyKey: `qr_daily/${today}/${customer.id}`
      });

      // Send QR code to Telegram if linked
      if (customer.telegram_user_id) {
        try {
          // Convert base64 data URL to Uint8Array for Telegram photo upload
          const base64Data = qrCodeDataUrl.replace(/^data:image\/png;base64,/, '');
          const binaryString = atob(base64Data);
          const bytes = new Uint8Array(binaryString.length);
          for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
          }

          // Send QR code via Telegram Bot API
          const formData = new FormData();
          formData.append('chat_id', customer.telegram_user_id.toString());
          formData.append('photo', new Blob([bytes], { type: 'image/png' }), 'qr-code.png');
          formData.append('caption', `🍽️ Your Frontier Meals QR Code\n📅 ${new Date(today).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}\n\nShow this at the kiosk to get your meal!`);

          const { TELEGRAM_BOT_TOKEN } = await import('$env/static/private');

          const telegramResponse = await fetch(
            `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendPhoto`,
            {
              method: 'POST',
              body: formData
            }
          );

          if (!telegramResponse.ok) {
            console.error(`[QR Job] Failed to send Telegram QR to customer ${customer.id}:`, await telegramResponse.text());
          } else {
            console.log(`[QR Job] Sent QR to Telegram for customer ${customer.id}`);
          }
        } catch (telegramError) {
          console.error(`[QR Job] Error sending QR to Telegram for customer ${customer.id}:`, telegramError);
          // Don't fail the whole job if Telegram delivery fails
        }
      }

      results.issued++;
      console.log(`[QR Job] Issued QR for customer ${customer.id} (${customer.email})`);

    } catch (error) {
      console.error(`[QR Job] Error issuing QR for customer ${customer.id}:`, error);
      results.errors.push({
        customer_id: customer.id,
        error: error instanceof Error ? error.message : 'Unknown error'
      });
    }
  }

  console.log(`[QR Job] Complete. Issued: ${results.issued}, Errors: ${results.errors.length}`);

  // TODO: If errors > 0, send alert to @noahchonlee via Telegram

  return results;
}
